<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Graduated Students {{$year}} - {{Auth::user()->school->school_name}}</title>
    <style>
        @page {
            size: A4 portrait; /* Graduation reports usually look better in portrait */
            margin: 1.5cm;
        }

        body {
            font-family: 'Helvetica', 'Arial', sans-serif;
            font-size: 11px;
            color: #333;
            line-height: 1.5;
            margin: 0;
            padding: 0;
        }

        /* Professional Header Layout */
        .header-table {
            width: 100%;
            border-bottom: 3px double #343a40;
            margin-bottom: 20px;
            padding-bottom: 10px;
        }

        .logo {
            max-height: 80px;
            width: auto;
        }

        .school-info {
            text-align: center;
        }

        .school-name {
            font-size: 22px;
            font-weight: bold;
            margin: 0;
            color: #1a2a3a;
            text-transform: uppercase;
        }

        .report-title {
            font-size: 14px;
            margin: 5px 0;
            color: #c0392b; /* Deep Red for "Official" status */
            font-weight: bold;
            letter-spacing: 1px;
        }

        .report-subtitle {
            font-size: 12px;
            color: #555;
            margin: 0;
        }

        /* Summary Box */
        .summary-table {
            width: 100%;
            margin-bottom: 20px;
            background-color: #f8f9fa;
            border: 1px solid #dee2e6;
            padding: 10px;
        }

        /* Data Table */
        .data-table {
            width: 100%;
            border-collapse: collapse;
        }

        .data-table th {
            background-color: #343a40;
            color: #ffffff;
            padding: 10px 5px;
            text-align: left;
            text-transform: uppercase;
            font-size: 10px;
            border: 1px solid #343a40;
        }

        .data-table td {
            padding: 8px 5px;
            border-bottom: 1px solid #dee2e6;
            vertical-align: middle;
        }

        /* Avatar Styling */
        .student-photo {
            width: 45px;
            height: 45px;
            border-radius: 4px; /* Squares often look more "official" for IDs */
            border: 1px solid #ccc;
            display: block;
        }

        .status-badge {
            background-color: #27ae60;
            color: white;
            padding: 3px 8px;
            border-radius: 12px;
            font-size: 9px;
            font-weight: bold;
            text-align: center;
        }

        /* Footer */
        footer {
            position: fixed;
            bottom: -30px;
            left: 0;
            right: 0;
            height: 35px;
            font-size: 9px;
            color: #777;
            border-top: 1px solid #ddd;
            padding-top: 10px;
        }

        .pagenum:before {
            content: counter(page);
        }

        .text-center { text-align: center; }
        .bold { font-weight: bold; }
    </style>
</head>
<body>

    <table class="header-table">
        <tr>
            <td width="20%">
                @if(Auth::user()->school->logo)
                    <img class="logo" src="{{ public_path('storage/logo/'. Auth::user()->school->logo) }}" alt="Logo">
                @endif
            </td>
            <td class="school-info">
                <div class="school-name">{{ Auth::user()->school->school_name }}</div>
                <div class="report-title">OFFICIAL GRADUATION REGISTRY</div>
                <div class="report-subtitle">Academic Year: {{ $year }} — Standard Seven</div>
            </td>
            <td width="20%" style="text-align: right;">
                {{-- Placeholder for QR code or School Stamp space --}}
            </td>
        </tr>
    </table>

    <table class="summary-table">
        <tr>
            <td>
                <strong>Report Date:</strong> {{ date('d M Y') }}<br>
                <strong>Total Graduates:</strong> {{ $studentExport->count() }}
            </td>
            <td style="text-align: right;">
                <strong>Generated By:</strong> {{ strtoupper(Auth::user()->first_name . ' ' . Auth::user()->last_name) }}<br>
                <strong>Status:</strong> Final Registry
            </td>
        </tr>
    </table>

    @if ($studentExport->isEmpty())
        <div class="text-center" style="padding: 50px; border: 1px dashed #ccc;">
            <p>No student records found for the {{ $year }} graduation period.</p>
        </div>
    @else
        <table class="data-table">
            <thead>
                <tr>
                    <th width="5%" class="text-center">#</th>
                    <th width="12%" class="text-center">Photo</th>
                    <th width="18%">Admission No</th>
                    <th width="45%">Full Name</th>
                    <th width="10%" class="text-center">Gender</th>
                    <th width="10%" class="text-center">Result</th>
                </tr>
            </thead>
            <tbody>
                @foreach($studentExport as $index => $student)
                    <tr>
                        <td class="text-center">{{ $index + 1 }}</td>
                        <td class="text-center">
                            @php
                                $imageName = $student->image;
                                $imagePath = public_path('storage/students/' . $imageName);
                                $displayImage = (!empty($imageName) && file_exists($imagePath))
                                    ? $imagePath
                                    : public_path('storage/students/student.jpg');
                            @endphp
                            <img class="student-photo" src="{{ $displayImage }}" alt="S">
                        </td>
                        <td class="bold">{{ strtoupper($student->admission_number) }}</td>
                        <td>{{ ucwords(strtolower($student->first_name.' '.$student->middle_name.' '.$student->last_name)) }}</td>
                        <td class="text-center">{{ strtoupper(substr($student->gender, 0, 1)) }}</td>
                        <td class="text-center">
                            <span class="status-badge">GRADUATED</span>
                        </td>
                    </tr>
                @endforeach
            </tbody>
        </table>
    @endif

    <footer>
        <table width="100%">
            <tr>
                <td align="left">Official Academic Record &copy; {{ date('Y') }}</td>
                <td align="center">Page <span class="pagenum"></span></td>
                <td align="right">Printed: {{ now()->format('d-m-Y H:i') }}</td>
            </tr>
        </table>
    </footer>

</body>
</html>
